### ISSUE TITLE
Running process via ProcessBuilder

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mernst/randoop#38]
```
An issue was reported against JVM related to Randoop: 
http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=7184771

It caused trouble with the default 60 seconds processing. I was able to make it 
work setting it to 10 seconds. I believe was a RAM issue.

```

Original issue reported on code.google.com by `javier.o...@gmail.com` on 18 Jul 2012 at 1:02

**Comment by mernst** [comment]
When you run Randoop, you can instruct the JVM to use more RAM.
For example, you can pass -J-Xmx1024M to give the JVM a gigabyte of memory for the heap.
