### ISSUE TITLE
Crash while generating serialized tests

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mernst/randoop#45]
```
What steps will reproduce the problem?
1. Download the org.apache.commons.collections package
2. Test the package (a list with all package classes provided with the 
--classlist parameter) with option --output-tests-serialized=randoop-tests.gz
3. Observe Randoop exiting with a Throwable thrown


What is the expected output? What do you see instead?

I expect to have tests in a file randoop-tests.gz and Randoop exiting normally. 
Instead, Randoop crashes with an error message attached.


What version of the product are you using? On what operating system?

Randoop 1.3.3. The operating system is GNU/Linux Trisquel 6.0.


Please provide any additional information below.

This is the command that I used to run Randoop:

java $JVM_FLAGS -ea -cp lib/randoop.jar:lib/junit4.jar:../examples/ 
randoop.main.Main gentests --classlist=classlist.txt 
--junit-output-dir=tests-round-1/ --junit-classname=Randoop1Test --timelimit=30 
--forbid-null=false --small-tests=true --testsperfile=1 
--check-object-contracts=false

File classlist.txt is attached.

```

Original issue reported on code.google.com by `ma...@cs.utah.edu` on 18 Nov 2013 at 6:31

Attachments:
* [classlist.txt](https://storage.googleapis.com/google-code-attachments/randoop/issue-45/comment-0/classlist.txt)
* [error-message.txt](https://storage.googleapis.com/google-code-attachments/randoop/issue-45/comment-0/error-message.txt)

**Comment by mernst** [comment]
I cannot reproduce the issue.
You didn't say which version of Apache Commons Collections you are using, but I didn't find org.apache.commons.collections.primitives.CharCollection, which is in your classlist.txt file, in either 3.2.1 or 4.0.
I'm also not sure what is in your ../examples folder.
If you provide a complete method of reproducing the issue, I will re-open it.
