### ISSUE TITLE
can't use @CheckRep

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mernst/randoop#46]
```
What steps will reproduce the problem?
1.download eclipse Helios for Java Developers
2. install plugin randoop
3. create project with method repOk and add @CheckRep comment in the top
4. import randoop.*

What is the expected output? What do you see instead?

eclipse don't find randoop
and I can't use @CheckRep
but if I quit @CheckRep the tests are generated well.

What version of the product are you using? On what operating system?
  Randoop Core/UI	0.1.0.201107281327	randoop.feature.group
  Eclipse IDE for Java Developers	1.3.2.20110218-0812	epp.package.java
  



```

Original issue reported on code.google.com by `madoeryp...@gmail.com` on 24 Jan 2014 at 12:12

**Comment by mernst** [comment]
Can you please try to reproduce this error from the command line?
Also, can you attach the exact file that you used?
That will help us understand the issue and ensure that the fix will work for you.
Thanks!

**Comment by mernst** [comment]
This sounds like either a problem with the Eclipse plug-in, or an incorrect use of Randoop.  The bug report doesn't include information about how to reproduce the problem, so I'm going to close the issue.
