### ISSUE TITLE
Fully Qualified Class Names Are Used Instead Of Imports

### ISSUE THREAD

**Issue by opticyclic** [mernst/randoop#50]
Randoop generates code like this:

    java.util.TreeSet var0 = new java.util.TreeSet();

Instead of

    import java.util.TreeSet;
    ...
    ...
    TreeSet var0 = new TreeSet();

**Comment by mernst** [comment]
That is correct, it does.  Is this a problem in practice?
Randoop can be passed multiple classes of the same name in different packages, and it would be difficult to choose which one should be imported in each file.  It's less error-prone, and requires less code, to use fully-qualified variable names throughout.
That said, when there is no ambiguity, using import statements would make the Randoop-generated tests easier to read.
If you wish to change this behavior, feel free to submit a pull request.

**Comment by nathanila** [comment]
Why was this issue closed?  The feature is not implemented.

This feature will improve the quality of the test cases.  One goal of the generated test cases is to achieve 100% instruction and branch coverage.  Another goal of the generated test cases is to make the code as human readable as possible.  Java code is not for machines to run.  Java code is for humans to read, understand and maintain.  Ideally, the generated test cases should be no different than what a human would write.

If there are multiple classes of the same name but different packages (a rare occurrence), then use the fully qualified name.

**Comment by mernst** [comment]
> Another goal of the generated test cases is to make the code as human readable as possible.

Your assertion is in conflict with the introduction to the Randoop manual.

That said, readability is a fine secondary goal.  Please feel free to submit a pull request that implements your suggestion.
