### ISSUE TITLE
Group Tests Together By Class

### ISSUE THREAD

**Issue by opticyclic** [mernst/randoop#53]
If I specify multiple `--testclass=...` options on the command line the test classes contain tests from different source classes.
I would rather have all my tests for a particular class residing in one test class rather than spread out over multiple test classes mixed with other tests.

**Comment by mernst** [comment]
Each test Daikon creates may invoke methods from arbitrary classes.  For example, a Daikon test might invoke 1 method from class A, then 8 methods from class B, then 1 method from class C.  It's not clear how you would want to segregate the tests or which class you would put the above test in.
