### ISSUE TITLE
Name Test Classes Better

### ISSUE THREAD

**Issue by opticyclic** [mernst/randoop#54]
Related to https://github.com/mernst/randoop/issues/53

Currently the generated test classes are named numerically.
e.g.
    
    RandoopTest.java
    RandoopTest0.java
    RandoopTest1.java
    RandoopTest2.java

It would be clearer if they were named based on the class under test.
e.g.

    RandoopTest.java
    RandoopTestCollections.java
    RandoopTestTreeSet.java
    RandoopTestHashMap.java

**Comment by mernst** [comment]
As mentioned in issue #53, it doesn't make sense to segregate Daikon tests by class under test, if you have supplied multiple test classes to Daikon.

If you want Daikon to create tests that call only methods from a single class, then supply just one test class to Daikon.  (This will result in worse test suites, though!)
