### ISSUE TITLE
Too Many Tests Are Generated - Use Parameterized Tests

### ISSUE THREAD

**Issue by opticyclic** [mernst/randoop#55]
I have a simple class like this
    
    public class Wallet {
        public final double cash;
    
        private Date date;
    
        public Wallet(double cash) {
            this.cash = cash;
            this.date = new Date();
        }
    }

36 separate test methods are created!
e.g. here are 2 testing similar cases (negative non-integers)
    
    public void test191() throws Throwable {
    
        if (debug) { System.out.println(); System.out.print("RandoopTest2.test191"); }
    
    
        com.me.Wallet var1 = new com.me.Wallet((-1.000001d));
    
    }
    
    public void test169() throws Throwable {
    
        if (debug) { System.out.println(); System.out.print("RandoopTest5.test169"); }
    
    
       com.me.Wallet var1 = new com.me.Wallet((-99.999d));
    
    }

All 36 can be re-written into a single test case like this  (https://github.com/junit-team/junit/wiki/Parameterized-tests)

    import junit.framework.*;
    import org.junit.runner.RunWith;
    import org.junit.runners.Parameterized;
    
    import java.util.Arrays;
    import java.util.Collection;
    
    @RunWith(Parameterized.class)
    public class WalletTest {
        @Parameterized.Parameters
        public static Collection<Object[]> data() {
            return Arrays.asList(new Object[][]{
                    {-99.999d, -99.999d}, {-1.000001d, -1.000001d}
            });
        }
    
        private int fInput;
    
        private int fExpected;
    
        public WalletTest(int input, int expected) {
            fInput= input;
            fExpected= expected;
        }
    
        @Test
        public void test() {
            if (debug) { System.out.println(); System.out.print("RandoopTest5.test169"); }
    
            com.me.Wallet var1 = new com.me.Wallet((fInput));
        }
    }
 

This can be greatly simplified by using TestNG.
http://howtodoinjava.com/2014/11/24/testng-test-parameters-through-dataprovider/

**Comment by mernst** [comment]
Such a change would be possible and would make the tests less bulky.

As background, Randoop's tests are not designed to be short or easy to read -- but you will only read them on the rare occasions when they fail and reveal a bug in your code.

If you want to implement this, here are some notes to help you get started.

Randoop creates tests by building on previous tests.  So you need to ensure that Randoop can still do so during its generation process.  That suggests to me that the most straightforward way to implement your suggestion would be as a postpass.  Let Randoop generate multiple tests, then coalesce them afterward before outputting them.

If you wanted to change Randoop's generation to produce such tests directly, then you would need to be careful to ensure that Randoop can still build upon shorter tests to create larger ones.
